default:
  image: docker.repo.splunkdev.net/ci-cd/ci-container:debian-buster

stages:
  - release

.go-cache:
  image: docker.repo.splunkdev.net/ci-cd/ci-container:golang-1.16
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p $GOPATH
    - go install github.com/goreleaser/goreleaser@v0.174.1
    - export PATH=$GOPATH/bin:$PATH
  cache:
    key: go-cache
    paths:
      - .go/pkg/mod
      - .go/bin

release:
  extends: .go-cache
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"
      - $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+.*/
  stage: build
  script: goreleaser release
  artifacts:
    paths:
      - dist/
